spring:
  application:
    name: im-gateway-service
  cloud:
    gateway:

      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://im-auth-service
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: lb://im-user-service
          predicates:
            - Path=/user/**

        - id: chat-service
          uri: lb://im-chat-service
          predicates:
            - Path=/api/v1/chat/**

        - id: chat-websocket
          uri: lb:ws://im-chat-service
            # uri: lb:ws://127.0.0.1:20007
          predicates:
            - Path=/chat/**


      predicate:
        cookie:
          enabled: true
#im-chat-service




    consul:
      host: localhost #consul注册地址
      port: 8500 #consul注册地址的端口，8500是默认端口
      discovery:
        heartbeat:
          enabled: true
        enabled: true #启用服务发现
        instance-id: ${spring.application.name}-${server.port}-${random.long}
        service-name: im-gateway-service
        port: 11777 # 服务端口
        register: true
        prefer-ip-address: true
        deregister: true
        ip-address: ${spring.cloud.client.ip-address}


